'use client';

import React, { useState } from 'react';
import { DailySummary } from '@/types/grid';
import { ChevronDown, ChevronUp, TrendingUp, Sun, Zap, Battery, Award, ArrowDownToLine, ArrowUpFromLine, Info } from 'lucide-react';
import { cn, getNeighborhoodDisplayName } from '@/lib/utils';

interface DailyComparisonTableProps {
  dailySummaries: DailySummary[];
  overallMetrics?: {
    avg_daily_reward: number;
    avg_stability: number;
    avg_grid_imports: number;
    avg_solar_utilization: number;
    avg_demand_satisfaction: number;
  };
}

export default function DailyComparisonTable({ 
  dailySummaries, 
  overallMetrics 
}: DailyComparisonTableProps) {
  const [expandedDay, setExpandedDay] = useState<number | null>(null);
  const [showTooltip, setShowTooltip] = useState<string | null>(null);
  
  if (dailySummaries.length === 0) return null;

  // Find best/worst for each metric
  const rewards = dailySummaries.map(d => d.total_reward);
  const stabilities = dailySummaries.map(d => d.avg_stability);
  const solarUtils = dailySummaries.map(d => d.solar_utilization);
  const demandSats = dailySummaries.map(d => d.demand_satisfaction);
  const gridImports = dailySummaries.map(d => d.grid_imports);
  
  const bestReward = Math.max(...rewards);
  const worstReward = Math.min(...rewards);
  const bestStability = Math.max(...stabilities);
  const bestSolar = Math.max(...solarUtils);
  const bestDemand = Math.max(...demandSats);
  const bestGridImport = Math.min(...gridImports); // Lower is better
  const worstGridImport = Math.max(...gridImports);

  const getValueColor = (value: number, best: number, worst: number, higherBetter = true) => {
    if (higherBetter) {
      if (value === best) return 'text-emerald-400 bg-emerald-400/10';
      if (value === worst) return 'text-rose-400 bg-rose-400/10';
    } else {
      if (value === best) return 'text-emerald-400 bg-emerald-400/10'; // best (lowest) for grid imports
      if (value === worst) return 'text-rose-400 bg-rose-400/10';
    }
    return 'text-slate-300';
  };

  const tooltips: Record<string, string> = {
    reward: 'Total reward earned by all agents. Higher = better decision-making.',
    stability: 'Grid balance measure. 60-80% is good; 100% is unrealistic due to solar/demand cycles.',
    solar: 'Percentage of solar energy used vs wasted. Higher = more efficient.',
    demand: 'Time steps where demand was met without blackout. Higher = more reliable.',
    gridImport: 'Energy bought from main grid (kWh). Lower = more self-sufficient.',
    totalDemand: 'Total energy consumed by this neighborhood during the day.',
    solarGen: 'Total solar energy generated by local panels.',
    gridImp: 'Energy purchased from the main power grid.',
    tradeIn: 'Energy received from neighboring areas.',
    tradeOut: 'Energy shared with neighboring areas.',
    batteryStart: 'Battery level at start of day.',
    batteryEnd: 'Battery level at end of day.'
  };

  return (
    <div className="bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 overflow-hidden">
      {/* Header */}
      <div className="p-4 border-b border-slate-700 bg-slate-900/50">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Award className="w-5 h-5 text-amber-400" />
            <h2 className="text-lg font-bold text-white">7-Day Performance Comparison</h2>
          </div>
          {overallMetrics && (
            <div className="flex items-center gap-4 text-xs">
              <span className="text-slate-400">
                Avg Reward: <span className="text-emerald-400 font-mono">{overallMetrics.avg_daily_reward.toFixed(0)}</span>
              </span>
              <span className="text-slate-400">
                Avg Stability: <span className="text-cyan-400 font-mono">{(overallMetrics.avg_stability * 100).toFixed(1)}%</span>
              </span>
            </div>
          )}
        </div>
        <p className="text-slate-500 text-xs mt-1">Click a row to see detailed energy breakdown per neighborhood</p>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="bg-slate-900/30 text-xs text-slate-400 uppercase tracking-wider">
              <th className="px-4 py-3 text-left font-medium">Day</th>
              <th className="px-4 py-3 text-right font-medium">
                <div 
                  className="flex items-center justify-end gap-1 cursor-help relative"
                  onMouseEnter={() => setShowTooltip('reward')}
                  onMouseLeave={() => setShowTooltip(null)}
                >
                  <TrendingUp className="w-3 h-3" />
                  Total Reward
                  <Info className="w-3 h-3 text-slate-500" />
                  {showTooltip === 'reward' && (
                    <div className="absolute bottom-full mb-2 right-0 bg-slate-700 text-slate-200 text-xs p-2 rounded shadow-lg w-48 z-10 normal-case">
                      {tooltips.reward}
                    </div>
                  )}
                </div>
              </th>
              <th className="px-4 py-3 text-right font-medium">
                <div 
                  className="flex items-center justify-end gap-1 cursor-help relative"
                  onMouseEnter={() => setShowTooltip('stability')}
                  onMouseLeave={() => setShowTooltip(null)}
                >
                  <Battery className="w-3 h-3" />
                  Stability
                  <Info className="w-3 h-3 text-slate-500" />
                  {showTooltip === 'stability' && (
                    <div className="absolute bottom-full mb-2 right-0 bg-slate-700 text-slate-200 text-xs p-2 rounded shadow-lg w-52 z-10 normal-case">
                      {tooltips.stability}
                    </div>
                  )}
                </div>
              </th>
              <th className="px-4 py-3 text-right font-medium">
                <div 
                  className="flex items-center justify-end gap-1 cursor-help relative"
                  onMouseEnter={() => setShowTooltip('solar')}
                  onMouseLeave={() => setShowTooltip(null)}
                >
                  <Sun className="w-3 h-3" />
                  Solar Util
                  <Info className="w-3 h-3 text-slate-500" />
                  {showTooltip === 'solar' && (
                    <div className="absolute bottom-full mb-2 right-0 bg-slate-700 text-slate-200 text-xs p-2 rounded shadow-lg w-48 z-10 normal-case">
                      {tooltips.solar}
                    </div>
                  )}
                </div>
              </th>
              <th className="px-4 py-3 text-right font-medium">
                <div 
                  className="flex items-center justify-end gap-1 cursor-help relative"
                  onMouseEnter={() => setShowTooltip('demand')}
                  onMouseLeave={() => setShowTooltip(null)}
                >
                  <Zap className="w-3 h-3" />
                  Demand Sat
                  <Info className="w-3 h-3 text-slate-500" />
                  {showTooltip === 'demand' && (
                    <div className="absolute bottom-full mb-2 right-0 bg-slate-700 text-slate-200 text-xs p-2 rounded shadow-lg w-48 z-10 normal-case">
                      {tooltips.demand}
                    </div>
                  )}
                </div>
              </th>
              <th className="px-4 py-3 text-right font-medium">
                <div 
                  className="flex items-center justify-end gap-1 cursor-help relative"
                  onMouseEnter={() => setShowTooltip('gridImport')}
                  onMouseLeave={() => setShowTooltip(null)}
                >
                  Grid Import
                  <Info className="w-3 h-3 text-slate-500" />
                  {showTooltip === 'gridImport' && (
                    <div className="absolute bottom-full mb-2 right-0 bg-slate-700 text-slate-200 text-xs p-2 rounded shadow-lg w-48 z-10 normal-case">
                      {tooltips.gridImport}
                    </div>
                  )}
                </div>
              </th>
              <th className="px-4 py-3 text-center font-medium">Details</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-700/50">
            {dailySummaries.map((summary) => (
              <React.Fragment key={summary.day}>
                <tr 
                  className="hover:bg-slate-800/30 transition-colors cursor-pointer"
                  onClick={() => setExpandedDay(expandedDay === summary.day ? null : summary.day)}
                >
                  <td className="px-4 py-3">
                    <span className="flex items-center gap-2">
                      <span className="w-7 h-7 rounded-lg bg-slate-700 flex items-center justify-center text-sm font-bold text-white">
                        {summary.day}
                      </span>
                      <span className="text-slate-400 text-sm">Day {summary.day}</span>
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <span className={cn(
                      "px-2 py-1 rounded font-mono text-sm",
                      getValueColor(summary.total_reward, bestReward, worstReward)
                    )}>
                      {summary.total_reward.toFixed(0)}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <span className={cn(
                      "px-2 py-1 rounded font-mono text-sm",
                      getValueColor(summary.avg_stability, bestStability, Math.min(...stabilities))
                    )}>
                      {(summary.avg_stability * 100).toFixed(1)}%
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <span className={cn(
                      "px-2 py-1 rounded font-mono text-sm",
                      getValueColor(summary.solar_utilization, bestSolar, Math.min(...solarUtils))
                    )}>
                      {summary.solar_utilization.toFixed(1)}%
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <span className={cn(
                      "px-2 py-1 rounded font-mono text-sm",
                      getValueColor(summary.demand_satisfaction, bestDemand, Math.min(...demandSats))
                    )}>
                      {summary.demand_satisfaction.toFixed(1)}%
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <span className={cn(
                      "px-2 py-1 rounded font-mono text-sm",
                      getValueColor(summary.grid_imports, bestGridImport, worstGridImport, false)
                    )}>
                      {summary.grid_imports.toFixed(1)} kWh
                    </span>
                  </td>
                  <td className="px-4 py-3 text-center">
                    <button className="p-1.5 rounded hover:bg-slate-700 transition-colors">
                      {expandedDay === summary.day ? (
                        <ChevronUp className="w-4 h-4 text-slate-400" />
                      ) : (
                        <ChevronDown className="w-4 h-4 text-slate-400" />
                      )}
                    </button>
                  </td>
                </tr>
                
                {/* Expanded Agent Details with Energy Breakdown */}
                {expandedDay === summary.day && (
                  <tr className="bg-slate-900/50">
                    <td colSpan={7} className="px-4 py-4">
                      <div className="mb-3 flex items-center gap-2 text-xs text-slate-400">
                        <span className="font-medium text-slate-300">Energy Breakdown by Neighborhood</span>
                        <span className="text-slate-500">|</span>
                        <span>All values in kWh unless stated</span>
                      </div>
                      
                      {/* Table header for agent details */}
                      <div className="overflow-x-auto">
                        <table className="w-full text-xs">
                          <thead>
                            <tr className="text-slate-500 border-b border-slate-700">
                              <th className="py-2 px-2 text-left">Neighborhood</th>
                              <th className="py-2 px-2 text-right">Reward</th>
                              <th className="py-2 px-2 text-right">
                                <span className="flex items-center justify-end gap-1">
                                  <Zap className="w-3 h-3" />
                                  Demand
                                </span>
                              </th>
                              <th className="py-2 px-2 text-right">
                                <span className="flex items-center justify-end gap-1">
                                  <Sun className="w-3 h-3 text-amber-400" />
                                  Solar Gen
                                </span>
                              </th>
                              <th className="py-2 px-2 text-right">Grid Import</th>
                              <th className="py-2 px-2 text-right">
                                <span className="flex items-center justify-end gap-1">
                                  <ArrowDownToLine className="w-3 h-3 text-cyan-400" />
                                  Trade In
                                </span>
                              </th>
                              <th className="py-2 px-2 text-right">
                                <span className="flex items-center justify-end gap-1">
                                  <ArrowUpFromLine className="w-3 h-3 text-rose-400" />
                                  Trade Out
                                </span>
                              </th>
                              <th className="py-2 px-2 text-right">
                                <span className="flex items-center justify-end gap-1">
                                  <Battery className="w-3 h-3" />
                                  Start
                                </span>
                              </th>
                              <th className="py-2 px-2 text-right">
                                <span className="flex items-center justify-end gap-1">
                                  <Battery className="w-3 h-3" />
                                  End
                                </span>
                              </th>
                              <th className="py-2 px-2 text-right">Demand Met</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-slate-700/30">
                            {summary.agents.map((agent, idx) => {
                              const agentRewards = summary.agents.map(a => a.reward);
                              const bestAgentReward = Math.max(...agentRewards);
                              const isBest = agent.reward === bestAgentReward;
                              
                              return (
                                <tr 
                                  key={agent.agent_id}
                                  className={cn(
                                    "transition-colors",
                                    isBest ? "bg-emerald-500/5" : "hover:bg-slate-800/30"
                                  )}
                                >
                                  <td className="py-2 px-2">
                                    <div className="flex items-center gap-2">
                                      <div className={cn(
                                        "w-6 h-6 rounded flex items-center justify-center text-xs font-bold",
                                        isBest
                                          ? "bg-emerald-500/20 text-emerald-400"
                                          : "bg-slate-700 text-slate-300"
                                      )}>
                                        {idx + 1}
                                      </div>
                                      <span className="text-slate-300">{getNeighborhoodDisplayName(agent.agent_id)}</span>
                                      {isBest && <Award className="w-3 h-3 text-amber-400" />}
                                    </div>
                                  </td>
                                  <td className={cn(
                                    "py-2 px-2 text-right font-mono",
                                    isBest ? "text-emerald-400" : "text-slate-300"
                                  )}>
                                    {agent.reward.toFixed(0)}
                                  </td>
                                  <td className="py-2 px-2 text-right font-mono text-amber-300">
                                    {agent.total_demand?.toFixed(1) || '—'}
                                  </td>
                                  <td className="py-2 px-2 text-right font-mono text-amber-400">
                                    {agent.solar_generated?.toFixed(1) || '—'}
                                  </td>
                                  <td className="py-2 px-2 text-right font-mono text-rose-400">
                                    {agent.grid_imported?.toFixed(1) || '—'}
                                  </td>
                                  <td className="py-2 px-2 text-right font-mono text-cyan-400">
                                    {agent.energy_traded_in?.toFixed(1) || '—'}
                                  </td>
                                  <td className="py-2 px-2 text-right font-mono text-rose-300">
                                    {agent.energy_traded_out?.toFixed(1) || '—'}
                                  </td>
                                  <td className="py-2 px-2 text-right font-mono text-slate-400">
                                    {agent.battery_start?.toFixed(1) || '—'}
                                  </td>
                                  <td className="py-2 px-2 text-right font-mono text-slate-300">
                                    {agent.battery_end?.toFixed(1) || '—'}
                                  </td>
                                  <td className="py-2 px-2 text-right">
                                    <span className={cn(
                                      "font-mono",
                                      (agent.demand_satisfaction || 0) >= 95 ? "text-emerald-400" :
                                      (agent.demand_satisfaction || 0) >= 80 ? "text-amber-400" : "text-rose-400"
                                    )}>
                                      {agent.demand_satisfaction?.toFixed(1) || '—'}%
                                    </span>
                                  </td>
                                </tr>
                              );
                            })}
                          </tbody>
                          {/* Day totals */}
                          <tfoot>
                            <tr className="border-t border-slate-600 bg-slate-800/30 font-medium">
                              <td className="py-2 px-2 text-slate-300">Day {summary.day} Total</td>
                              <td className="py-2 px-2 text-right font-mono text-cyan-400">
                                {summary.total_reward.toFixed(0)}
                              </td>
                              <td className="py-2 px-2 text-right font-mono text-amber-300">
                                {summary.total_demand?.toFixed(1) || '—'}
                              </td>
                              <td className="py-2 px-2 text-right font-mono text-amber-400">
                                {summary.total_solar_generated?.toFixed(1) || '—'}
                              </td>
                              <td className="py-2 px-2 text-right font-mono text-rose-400">
                                {summary.grid_imports.toFixed(1)}
                              </td>
                              <td colSpan={3} className="py-2 px-2 text-center text-slate-500 text-xs">
                                Net trades balance out across grid
                              </td>
                              <td className="py-2 px-2 text-right font-mono text-cyan-400">
                                {(summary.avg_stability * 100).toFixed(1)}%
                              </td>
                              <td className="py-2 px-2 text-right font-mono text-emerald-400">
                                {summary.demand_satisfaction.toFixed(1)}%
                              </td>
                            </tr>
                          </tfoot>
                        </table>
                      </div>
                      
                      {/* Energy flow summary */}
                      <div className="mt-4 grid grid-cols-4 gap-3">
                        <div className="bg-slate-800/50 rounded-lg p-3 border border-slate-700/50">
                          <div className="flex items-center gap-2 mb-1">
                            <Sun className="w-4 h-4 text-amber-400" />
                            <span className="text-slate-400 text-xs">Solar Generated</span>
                          </div>
                          <span className="text-lg font-mono text-amber-400">
                            {summary.total_solar_generated?.toFixed(0) || '—'} kWh
                          </span>
                        </div>
                        <div className="bg-slate-800/50 rounded-lg p-3 border border-slate-700/50">
                          <div className="flex items-center gap-2 mb-1">
                            <Zap className="w-4 h-4 text-cyan-400" />
                            <span className="text-slate-400 text-xs">Solar Used</span>
                          </div>
                          <span className="text-lg font-mono text-cyan-400">
                            {summary.total_solar_used?.toFixed(0) || '—'} kWh
                          </span>
                          <span className="text-xs text-slate-500 ml-2">
                            ({summary.solar_utilization.toFixed(0)}%)
                          </span>
                        </div>
                        <div className="bg-slate-800/50 rounded-lg p-3 border border-slate-700/50">
                          <div className="flex items-center gap-2 mb-1">
                            <ArrowDownToLine className="w-4 h-4 text-rose-400" />
                            <span className="text-slate-400 text-xs">Grid Imported</span>
                          </div>
                          <span className="text-lg font-mono text-rose-400">
                            {summary.grid_imports.toFixed(0)} kWh
                          </span>
                        </div>
                        <div className="bg-slate-800/50 rounded-lg p-3 border border-slate-700/50">
                          <div className="flex items-center gap-2 mb-1">
                            <Battery className="w-4 h-4 text-emerald-400" />
                            <span className="text-slate-400 text-xs">Avg Stability</span>
                          </div>
                          <span className={cn(
                            "text-lg font-mono",
                            summary.avg_stability >= 0.7 ? "text-emerald-400" :
                            summary.avg_stability >= 0.5 ? "text-amber-400" : "text-rose-400"
                          )}>
                            {(summary.avg_stability * 100).toFixed(1)}%
                          </span>
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
              </React.Fragment>
            ))}
          </tbody>
          
          {/* Summary Footer */}
          {overallMetrics && (
            <tfoot>
              <tr className="bg-slate-900/50 border-t border-slate-600">
                <td className="px-4 py-3 font-semibold text-slate-300">7-Day Average</td>
                <td className="px-4 py-3 text-right font-mono text-cyan-400 font-semibold">
                  {overallMetrics.avg_daily_reward.toFixed(0)}
                </td>
                <td className="px-4 py-3 text-right font-mono text-cyan-400 font-semibold">
                  {(overallMetrics.avg_stability * 100).toFixed(1)}%
                </td>
                <td className="px-4 py-3 text-right font-mono text-cyan-400 font-semibold">
                  {overallMetrics.avg_solar_utilization.toFixed(1)}%
                </td>
                <td className="px-4 py-3 text-right font-mono text-cyan-400 font-semibold">
                  {overallMetrics.avg_demand_satisfaction.toFixed(1)}%
                </td>
                <td className="px-4 py-3 text-right font-mono text-slate-400">
                  {overallMetrics.avg_grid_imports.toFixed(1)} kWh/day
                </td>
                <td className="px-4 py-3"></td>
              </tr>
            </tfoot>
          )}
        </table>
      </div>
      
      {/* Legend */}
      <div className="px-4 py-3 border-t border-slate-700 bg-slate-900/30 flex items-center gap-4 text-xs text-slate-500">
        <span className="flex items-center gap-1">
          <span className="w-3 h-3 rounded bg-emerald-400/20 border border-emerald-400/50"></span>
          Best performance
        </span>
        <span className="flex items-center gap-1">
          <span className="w-3 h-3 rounded bg-rose-400/20 border border-rose-400/50"></span>
          Needs improvement
        </span>
        <span className="flex items-center gap-1">
          <Info className="w-3 h-3" />
          Hover headers for explanations
        </span>
      </div>
    </div>
  );
}
